### ISSUE TITLE
Updating Function Briefs

### ISSUE THREAD

**Issue by nclesko** [AA0CN/Arduino_CWBeacon#3]
nclesko will update a function brief in cw_beacon.ino.

- [x] Create a branch
- [x] Edit the file
- [x] Commit the changes
- [x] Create a Pull Request
- [x] Request a Review
- [x] Make more changes
- [x] Get an approval
- [x] Merge the Pull Request

**Comment by NobuSuginaka** [comment]
Good idea.

**Comment by AA0CN** [comment]
Resolved by Pull Request #4
